### ISSUE TITLE
Wiki access

### ISSUE THREAD

**Issue by OGMP-Gyrth** [OvergrowthCommunity/Community-OG-Campaign#2]
Could you see if you have permission to edit the wiki? Trying to edit some of the settings.

**Comment by Omegakatze** [comment]
I do have permission

**Comment by OGMP-Gyrth** [comment]
@BusterCharlie does this work?

**Comment by lMNGl** [comment]
How do I become a member? What is a member? Is that the same as getting *"write access"*?

**Comment by lMNGl** [comment]
Do I have to be a member in order to edit the wiki?

**Comment by OGMP-Gyrth** [comment]
I've send you an invite that you still haven't accepted. Dipshit.

**Comment by lMNGl** [comment]
Where do I receive that, dipshit.

**Comment by Omegakatze** [comment]
There's a bell on the page, I don't remember if that's the correct one though
