### ISSUE TITLE
Suggestions from writers for Slang?

### ISSUE THREAD

**Issue by BusterCharlie** [OvergrowthCommunity/Community-OG-Campaign#4]
@OvergrowthCommunity/Writers

I'd love for people to come up with Slang terms, slurs or nicknames critters would call each other.

**Comment by BusterCharlie** [comment]
@OvergrowthCommunity/writers If anyone would like to submit suggestions or discuss this further feel free, but if nobody else is interested we can close this.

**Comment by Omegakatze** [comment]
Well I would think that they could be named after what makes them "insert here* like uhh 
Ex. 
1. Cats=Clawfronts
2. Dogs=Barkmouths
3. Rabbits=Kickfoots
4. Rats=Smallsneaks
5. Wolves=Allhunter(couldn't think of anything better)

**Comment by BusterCharlie** [comment]
Rats: pisstrail, baldtails, corpse-eater

A cat who wishes to have romantic relationship with a rabbit: Thumper

**Comment by BusterCharlie** [comment]
Started a conversation in the writer's team discussion.
